#!.tox/py3/bin/python

import sys
from unittest.mock import patch

from pydoc_markdown.main import cli


with patch('charmhelpers.core.hookenv.metadata') as metadata:
    metadata.return_value = {
        'requires': {'aws': {'interface': 'aws-integration'}},
        'provides': {'aws': {'interface': 'aws-integration'}},
    }
    sys.path.insert(0, '.')
    cli()
